### ISSUE TITLE
Permissions to merge PRs in this repo

### ISSUE THREAD

**Issue by geekygirldawn** [cncf/project-template#42]
I'm not sure who has permission to merge PRs in this repo, so I keep pinging @amye to merge things. Would it be possible for @jberkus and I to get the permissions required to merge PRs?

I promise that we won't merge anything unless we have TOC liaison approval, but allowing us to merge would reduce the load for Amye and the TOC :) 

cc: @thefoxatwork & @dzolotusky

**Comment by TheFoxAtWork** [comment]
Looks like the admins listing needs updated, but @jberkus : 

https://github.com/cncf/project-template/blob/main/.github/settings.yml

**Comment by dzolotusky** [comment]
Any reason not to add @geekygirldawn to the admin list, in exchange for having her cleaning up / updating all of the names in that file?

**Comment by TheFoxAtWork** [comment]
I concur with adding @geekygirldawn to the admin list. Having at least two-three individuals from TAG CS as admins on this repo (since that group is largely generating content in this repo and has processes to ensure appropriate approvals are in place) makes sense and would allow PRs to still receive the appropriate amount of non-author reviewers.

**Comment by amye** [comment]
I think this is under @RobertKielty's area to add in admins into either Sheriff or Clowarden.
@jeefy for visibility

**Comment by geekygirldawn** [comment]
After talking to @RobertKielty - permissions changes need to be made in cncf/people, so I submitted the PR there and will close this issue once I've confirmed that the permissions changes are working.
